using CustomSettingManagement.EntityFrameworkCore;
using Xunit;

namespace CustomSettingManagement.EntityFrameworkCore;

public class CustomSettingManagementEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<CustomSettingManagementEntityFrameworkCoreFixture>
{

}
