using Volo.Abp;

namespace CustomSettingManagement.EntityFrameworkCore;

public abstract class CustomSettingManagementEntityFrameworkCoreTestBase : CustomSettingManagementTestBase<CustomSettingManagementEntityFrameworkCoreTestModule>
{

}
